# Only for development purposes

version: "3"

services:
  vosstraat:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JWT_KEY: ${JWT_KEY:?error}
    ports:
      - "80:80"
